version: '3.1'
services:
  app:
    container_name: todo-application
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgre_db
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=$POSTGRES_PGDATA
volumes:
  postgresql_db: {}